const moment = (time, eventName) => ({ time, eventName });
const schedule = {
  sunday: [
    moment("2:00PM", "Registration Begins"),
    moment("4:30PM", "Orientation"),
    moment("5:30PM", "Dinner"),
    moment("6:30PM", "Evening Activity"),
    moment("7:30PM", "Campfire"),
    moment("8:45", "John/Rosie Chat"),
    moment("9:30", "Taps"),
  ],
  normal: [
    moment("7:00AM", "Reveille"),
    moment("7:05AM", "Polar Bear Dip"),
    moment("7:20AM", "Polar Bear Dip last call"),
    moment("7:30AM", "Breakfast prep"),
    moment("7:45AM", "Flag Raising/Breakfast"),
    moment("8:30AM", "Morning Assembly"),
    moment("9:00AM", "Cabin duties"),
    moment("9:30AM", "Activity Period #1 "),
    moment("10:20AM", "Activity Period #2"),
    moment("11:10AM", "Free Time #1"),
    moment("12:00PM", "Lunch Prep/Back to cabins"),
    moment("12:15PM", "Lunch"),
    moment("1:30PM", "Siesta"),
    moment("2:00PM", "Free Time #2"),
    moment("2:50PM", "Activity Period #3 (All week activity"),
    moment("3:40PM", "Activity Period #4"),
    moment("4:30PM", "Free Time #3"),
    moment("5:20PM", "Dinner Prep / Back to cabins"),
    moment("5:30PM", "Flag Lowering/Dinner"),
    moment("6:30PM", "Cabin Activity"),
    moment("7:30PM", "Evening Activity"),
    moment("9:30PM", "Taps"),
  ],
  friday: [
    moment("7:00AM", "Reveille"),
    moment("7:05AM", "Polar Bear Dip"),
    moment("7:20AM", "Polar Bear Dip last call"),
    moment("7:30AM", "Breakfast prep"),
    moment("7:45AM", "Flag Raising/Breakfast"),
    moment("8:30AM", "Morning Assembly"),
    moment("9:00AM", "Cabin duties"),
    moment("9:30AM", "Activity Period #1 "),
    moment("10:20AM", "Activity Period #2"),
    moment("11:10AM", "Free Time #1"),
    moment("12:00PM", "Lunch Prep/Back to cabins"),
    moment("12:15PM", "Lunch & Bullfrogs"),
    moment("1:45PM", "Siesta"),
    moment("2:15PM", "All Camp Freetime"),
    moment("3:05PM", "Trash Pick Up"),
    moment("3:35PM", "Drama Video"),
    moment("4:00PM", "Camper Awards"),
    moment("4:45PM", "Back to cabins. Ready for pickup"),
    moment("5:00PM", "Pickup begins"),
    moment("5:45PM", "Ceremony"),
  ],
  lateFriday: [
    moment("7:00AM", "Reveille"),
    moment("7:05AM", "Polar Bear Dip"),
    moment("7:20AM", "Polar Bear Dip last call"),
    moment("7:30AM", "Breakfast prep"),
    moment("7:45AM", "Flag Raising/Breakfast"),
    moment("8:30AM", "Morning Assembly"),
    moment("9:00AM", "Cabin duties"),
    moment("9:30AM", "Activity Period #1 "),
    moment("10:20AM", "Activity Period #2"),
    moment("11:10AM", "Free Time #1"),
    moment("12:00PM", "Lunch Prep/Back to cabins"),
    moment("12:15PM", "Lunch & Bullfrogs"),
    moment("1:45PM", "Siesta"),
    moment("2:15PM", "All Camp Freetime"),
    moment("3:05PM", "Trash Pick Up"),
    moment("3:35PM", "Drama Video"),
    moment("4:00PM", "Camper Awards"),
    moment("4:45PM", "Back to cabins. Ready for pickup"),
    moment("5:00PM", "Pickup begins"),
    moment("5:45PM", "Ceremony"),
  ],
};

module.exports = schedule;
