module.exports = {
  unmappedCamperResult: [
    {
      first_name: "Tyler",
      last_name: "Knapp",
      gender: "Male",
      id: 409,
      age: 8,
      week_number: 1,
      week_title: "Around the world week",
      camper_week_id: 606,
      cabin_session_id_id: null,
      cabin_name: null,
    },
    {
      first_name: "Tyler",
      last_name: "Knapp",
      gender: "Male",
      id: 409,
      age: 8,
      week_number: 2,
      week_title: "Time Travel week",
      camper_week_id: 605,
      cabin_session_id: 55,
      cabin_name: "8",
    },
    {
      first_name: "Anja",
      last_name: "Golden",
      gender: "Female",
      id: 402,
      age: 7,
      week_number: 1,
      week_title: "Around the world week",
      camper_week_id: 608,
      cabin_session_id: 13,
      cabin_name: "Eagles",
    },
    {
      first_name: "Sokhna",
      last_name: "Fall",
      gender: "Female",
      id: 401,
      age: 10,
      week_number: 1,
      week_title: "Around the world week",
      camper_week_id: 608,
      cabin_session_id: 13,
      cabin_name: "Eagles",
    },
  ],

  mappedCampers: [
    {
      firstName: "Tyler",
      lastName: "Knapp",
      age: 8,
      id: 409,
      gender: "Male",
      weeks: [
        {
          number: 1,
          title: "Around the world week",
          id: 606,
          cabinName: null,
          cabinSessionId: null,
        },
        {
          number: 2,
          title: "Time Travel week",
          id: 605,
          cabinName: "8",
          cabinSessionId: 55,
        },
      ],
    },
    {
      firstName: "Anja",
      lastName: "Golden",
      gender: "Female",
      id: 402,
      age: 7,
      weeks: [
        {
          number: 1,
          title: "Around the world week",
          id: 608,
          cabinSessionId: 13,
          cabinName: "Eagles",
        },
      ],
    },
    {
      firstName: "Sokhna",
      lastName: "Fall",
      gender: "Female",
      id: 401,
      age: 10,
      weeks: [
        {
          number: 1,
          title: "Around the world week",
          id: 608,
          cabinSessionId: 13,
          cabinName: "Eagles",
        },
      ],
    },
  ],
};
